# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_name', models.CharField(max_length=30)),
                ('logo_type', models.CharField(max_length=30)),
                ('software_used', models.CharField(max_length=100)),
                ('requested_by', models.CharField(max_length=30)),
                ('created_by', models.CharField(max_length=30)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
