# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='logo_img',
            field=models.FileField(default='None', upload_to=''),
        ),
    ]
