# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('discription', models.TextField()),
                ('logo_type', models.CharField(max_length=30)),
                ('usage', models.CharField(max_length=30)),
                ('is_created', models.BooleanField(default='False')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
